### ISSUE TITLE
Use of realloc without checking return value

### ISSUE THREAD

**Issue by rechtem** [jcorporation/sds#34]
https://github.com/jcorporation/sds/blob/3f3ba2ad2a5bc85de160932afcef118ed1179764/sds.c#L1283

**Comment by jcorporation** [comment]
Seems to be bug, we should report this upstream.

I will fix it in my fork and prepare a pull request, but upstream repo is not really active. Reporting this to redis could be the better way.

**Comment by rechtem** [comment]
Hello Jürgen, 

I let you report it, should you think it would be useful for their project. 

Marc 


De: "Jürgen Mang" ***@***.***> 
À: "jcorporation/sds" ***@***.***> 
Cc: "rechtem" ***@***.***>, "Author" ***@***.***> 
Envoyé: Jeudi 31 Août 2023 08:35:22 
Objet: Re: [jcorporation/sds] Use of realloc without checking return value (Issue #34) 





Seems to be bug, we should report this upstream. 

I will fix it in my fork and prepare a pull request, but upstream repo is not really active. Reporting this to redis could be the better way.

**Comment by jcorporation** [comment]
fixed
